<?php
/**
 * EmailResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  CollingMedia\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace CollingMedia\Client\Model;

use \ArrayAccess;

/**
 * EmailResponse Class Doc Comment
 *
 * @category    Class */
/**
 * @package     CollingMedia\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EmailResponse implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'EmailResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'created_at' => '\DateTime',
        'description' => 'string',
        'folder' => '\CollingMedia\Client\Model\Folder',
        'from_email' => 'string',
        'from_name' => 'string',
        'id' => 'int',
        'name' => 'string',
        'operational' => 'bool',
        'publish_to_msi' => 'bool',
        'reply_email' => 'string',
        'status' => 'string',
        'subject' => 'string',
        'template' => 'int',
        'text_only' => 'bool',
        'updated_at' => '\DateTime',
        'url' => 'string',
        'version' => 'int',
        'web_view' => 'bool',
        'workspace' => 'string'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'created_at' => 'createdAt',
        'description' => 'description',
        'folder' => 'folder',
        'from_email' => 'fromEmail',
        'from_name' => 'fromName',
        'id' => 'id',
        'name' => 'name',
        'operational' => 'operational',
        'publish_to_msi' => 'publishToMSI',
        'reply_email' => 'replyEmail',
        'status' => 'status',
        'subject' => 'subject',
        'template' => 'template',
        'text_only' => 'textOnly',
        'updated_at' => 'updatedAt',
        'url' => 'url',
        'version' => 'version',
        'web_view' => 'webView',
        'workspace' => 'workspace'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'created_at' => 'setCreatedAt',
        'description' => 'setDescription',
        'folder' => 'setFolder',
        'from_email' => 'setFromEmail',
        'from_name' => 'setFromName',
        'id' => 'setId',
        'name' => 'setName',
        'operational' => 'setOperational',
        'publish_to_msi' => 'setPublishToMsi',
        'reply_email' => 'setReplyEmail',
        'status' => 'setStatus',
        'subject' => 'setSubject',
        'template' => 'setTemplate',
        'text_only' => 'setTextOnly',
        'updated_at' => 'setUpdatedAt',
        'url' => 'setUrl',
        'version' => 'setVersion',
        'web_view' => 'setWebView',
        'workspace' => 'setWorkspace'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'created_at' => 'getCreatedAt',
        'description' => 'getDescription',
        'folder' => 'getFolder',
        'from_email' => 'getFromEmail',
        'from_name' => 'getFromName',
        'id' => 'getId',
        'name' => 'getName',
        'operational' => 'getOperational',
        'publish_to_msi' => 'getPublishToMsi',
        'reply_email' => 'getReplyEmail',
        'status' => 'getStatus',
        'subject' => 'getSubject',
        'template' => 'getTemplate',
        'text_only' => 'getTextOnly',
        'updated_at' => 'getUpdatedAt',
        'url' => 'getUrl',
        'version' => 'getVersion',
        'web_view' => 'getWebView',
        'workspace' => 'getWorkspace'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    const VERSION_1 = 1;
    const VERSION_2 = 2;
    

    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getVersionAllowableValues()
    {
        return [
            self::VERSION_1,
            self::VERSION_2,
        ];
    }
    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['created_at'] = isset($data['created_at']) ? $data['created_at'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['folder'] = isset($data['folder']) ? $data['folder'] : null;
        $this->container['from_email'] = isset($data['from_email']) ? $data['from_email'] : null;
        $this->container['from_name'] = isset($data['from_name']) ? $data['from_name'] : null;
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['operational'] = isset($data['operational']) ? $data['operational'] : null;
        $this->container['publish_to_msi'] = isset($data['publish_to_msi']) ? $data['publish_to_msi'] : null;
        $this->container['reply_email'] = isset($data['reply_email']) ? $data['reply_email'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['subject'] = isset($data['subject']) ? $data['subject'] : null;
        $this->container['template'] = isset($data['template']) ? $data['template'] : null;
        $this->container['text_only'] = isset($data['text_only']) ? $data['text_only'] : null;
        $this->container['updated_at'] = isset($data['updated_at']) ? $data['updated_at'] : null;
        $this->container['url'] = isset($data['url']) ? $data['url'] : null;
        $this->container['version'] = isset($data['version']) ? $data['version'] : null;
        $this->container['web_view'] = isset($data['web_view']) ? $data['web_view'] : null;
        $this->container['workspace'] = isset($data['workspace']) ? $data['workspace'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];
        if ($this->container['folder'] === null) {
            $invalid_properties[] = "'folder' can't be null";
        }
        if ($this->container['from_email'] === null) {
            $invalid_properties[] = "'from_email' can't be null";
        }
        if ($this->container['from_name'] === null) {
            $invalid_properties[] = "'from_name' can't be null";
        }
        if ($this->container['operational'] === null) {
            $invalid_properties[] = "'operational' can't be null";
        }
        if ($this->container['publish_to_msi'] === null) {
            $invalid_properties[] = "'publish_to_msi' can't be null";
        }
        if ($this->container['reply_email'] === null) {
            $invalid_properties[] = "'reply_email' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalid_properties[] = "'status' can't be null";
        }
        if ($this->container['subject'] === null) {
            $invalid_properties[] = "'subject' can't be null";
        }
        if ($this->container['template'] === null) {
            $invalid_properties[] = "'template' can't be null";
        }
        if ($this->container['text_only'] === null) {
            $invalid_properties[] = "'text_only' can't be null";
        }
        $allowed_values = ["1", "2"];
        if (!in_array($this->container['version'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'version', must be one of #{allowed_values}.";
        }

        if ($this->container['web_view'] === null) {
            $invalid_properties[] = "'web_view' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        if ($this->container['folder'] === null) {
            return false;
        }
        if ($this->container['from_email'] === null) {
            return false;
        }
        if ($this->container['from_name'] === null) {
            return false;
        }
        if ($this->container['operational'] === null) {
            return false;
        }
        if ($this->container['publish_to_msi'] === null) {
            return false;
        }
        if ($this->container['reply_email'] === null) {
            return false;
        }
        if ($this->container['status'] === null) {
            return false;
        }
        if ($this->container['subject'] === null) {
            return false;
        }
        if ($this->container['template'] === null) {
            return false;
        }
        if ($this->container['text_only'] === null) {
            return false;
        }
        $allowed_values = ["1", "2"];
        if (!in_array($this->container['version'], $allowed_values)) {
            return false;
        }
        if ($this->container['web_view'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets created_at
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     * @param \DateTime $created_at Datetime the asset was created
     * @return $this
     */
    public function setCreatedAt($created_at)
    {
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets description
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     * @param string $description Description of the asset
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets folder
     * @return \CollingMedia\Client\Model\Folder
     */
    public function getFolder()
    {
        return $this->container['folder'];
    }

    /**
     * Sets folder
     * @param \CollingMedia\Client\Model\Folder $folder JSON representation of parent folder, with members 'id', and 'type' which may be 'Folder' or 'Program'
     * @return $this
     */
    public function setFolder($folder)
    {
        $this->container['folder'] = $folder;

        return $this;
    }

    /**
     * Gets from_email
     * @return string
     */
    public function getFromEmail()
    {
        return $this->container['from_email'];
    }

    /**
     * Sets from_email
     * @param string $from_email From-address of the Email
     * @return $this
     */
    public function setFromEmail($from_email)
    {
        $this->container['from_email'] = $from_email;

        return $this;
    }

    /**
     * Gets from_name
     * @return string
     */
    public function getFromName()
    {
        return $this->container['from_name'];
    }

    /**
     * Sets from_name
     * @param string $from_name From-name of the Email
     * @return $this
     */
    public function setFromName($from_name)
    {
        $this->container['from_name'] = $from_name;

        return $this;
    }

    /**
     * Gets id
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     * @param int $id Id of the asset
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     * @param string $name Name of the asset
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets operational
     * @return bool
     */
    public function getOperational()
    {
        return $this->container['operational'];
    }

    /**
     * Sets operational
     * @param bool $operational Whether the email is operational.  Operational emails bypass unsubscribe status.  Defaults to false
     * @return $this
     */
    public function setOperational($operational)
    {
        $this->container['operational'] = $operational;

        return $this;
    }

    /**
     * Gets publish_to_msi
     * @return bool
     */
    public function getPublishToMsi()
    {
        return $this->container['publish_to_msi'];
    }

    /**
     * Sets publish_to_msi
     * @param bool $publish_to_msi Whether the email is published to Marketo Sales Insight
     * @return $this
     */
    public function setPublishToMsi($publish_to_msi)
    {
        $this->container['publish_to_msi'] = $publish_to_msi;

        return $this;
    }

    /**
     * Gets reply_email
     * @return string
     */
    public function getReplyEmail()
    {
        return $this->container['reply_email'];
    }

    /**
     * Sets reply_email
     * @param string $reply_email Reply-To address of the Email
     * @return $this
     */
    public function setReplyEmail($reply_email)
    {
        $this->container['reply_email'] = $reply_email;

        return $this;
    }

    /**
     * Gets status
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     * @param string $status Status filter for draft or approved versions
     * @return $this
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets subject
     * @return string
     */
    public function getSubject()
    {
        return $this->container['subject'];
    }

    /**
     * Sets subject
     * @param string $subject Subject Line of the Email
     * @return $this
     */
    public function setSubject($subject)
    {
        $this->container['subject'] = $subject;

        return $this;
    }

    /**
     * Gets template
     * @return int
     */
    public function getTemplate()
    {
        return $this->container['template'];
    }

    /**
     * Sets template
     * @param int $template Id of the parent template
     * @return $this
     */
    public function setTemplate($template)
    {
        $this->container['template'] = $template;

        return $this;
    }

    /**
     * Gets text_only
     * @return bool
     */
    public function getTextOnly()
    {
        return $this->container['text_only'];
    }

    /**
     * Sets text_only
     * @param bool $text_only Setting to include text-only version of email when sent
     * @return $this
     */
    public function setTextOnly($text_only)
    {
        $this->container['text_only'] = $text_only;

        return $this;
    }

    /**
     * Gets updated_at
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     * @param \DateTime $updated_at Datetime the asset was most recently updated
     * @return $this
     */
    public function setUpdatedAt($updated_at)
    {
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Gets url
     * @return string
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     * @param string $url Url of the asset in the Marketo UI
     * @return $this
     */
    public function setUrl($url)
    {
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets version
     * @return int
     */
    public function getVersion()
    {
        return $this->container['version'];
    }

    /**
     * Sets version
     * @param int $version The type version of the email
     * @return $this
     */
    public function setVersion($version)
    {
        $allowed_values = array('1', '2');
        if (!is_null($version) && (!in_array($version, $allowed_values))) {
            throw new \InvalidArgumentException("Invalid value for 'version', must be one of '1', '2'");
        }
        $this->container['version'] = $version;

        return $this;
    }

    /**
     * Gets web_view
     * @return bool
     */
    public function getWebView()
    {
        return $this->container['web_view'];
    }

    /**
     * Sets web_view
     * @param bool $web_view Whether 'View as Webpage' function is enabled for the email
     * @return $this
     */
    public function setWebView($web_view)
    {
        $this->container['web_view'] = $web_view;

        return $this;
    }

    /**
     * Gets workspace
     * @return string
     */
    public function getWorkspace()
    {
        return $this->container['workspace'];
    }

    /**
     * Sets workspace
     * @param string $workspace Name of the workspace
     * @return $this
     */
    public function setWorkspace($workspace)
    {
        $this->container['workspace'] = $workspace;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\CollingMedia\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\CollingMedia\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


