<?php
/**
 * CreateEmailRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CollingMedia\Client;

/**
 * CreateEmailRequestTest Class Doc Comment
 *
 * @category    Class */
// * @description CreateEmailRequest
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateEmailRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "CreateEmailRequest"
     */
    public function testCreateEmailRequest()
    {

    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {

    }

    /**
     * Test attribute "folder"
     */
    public function testPropertyFolder()
    {

    }

    /**
     * Test attribute "from_email"
     */
    public function testPropertyFromEmail()
    {

    }

    /**
     * Test attribute "from_name"
     */
    public function testPropertyFromName()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "operational"
     */
    public function testPropertyOperational()
    {

    }

    /**
     * Test attribute "reply_email"
     */
    public function testPropertyReplyEmail()
    {

    }

    /**
     * Test attribute "subject"
     */
    public function testPropertySubject()
    {

    }

    /**
     * Test attribute "template"
     */
    public function testPropertyTemplate()
    {

    }

    /**
     * Test attribute "text_only"
     */
    public function testPropertyTextOnly()
    {

    }

}
