<?php
/**
 * FormVisibilityRuleDTOTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CollingMedia\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CollingMedia\Client;

/**
 * FormVisibilityRuleDTOTest Class Doc Comment
 *
 * @category    Class */
// * @description FormVisibilityRuleDTO
/**
 * @package     CollingMedia\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FormVisibilityRuleDTOTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "FormVisibilityRuleDTO"
     */
    public function testFormVisibilityRuleDTO()
    {

    }

    /**
     * Test attribute "alt_label"
     */
    public function testPropertyAltLabel()
    {

    }

    /**
     * Test attribute "operator"
     */
    public function testPropertyOperator()
    {

    }

    /**
     * Test attribute "picklist_filter_values"
     */
    public function testPropertyPicklistFilterValues()
    {

    }

    /**
     * Test attribute "subject_field"
     */
    public function testPropertySubjectField()
    {

    }

    /**
     * Test attribute "values"
     */
    public function testPropertyValues()
    {

    }

}
