<?php
/**
 * LandingPageContentResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  CollingMedia\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CollingMedia\Client;

/**
 * LandingPageContentResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description LandingPageContentResponse
/**
 * @package     CollingMedia\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LandingPageContentResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "LandingPageContentResponse"
     */
    public function testLandingPageContentResponse()
    {

    }

    /**
     * Test attribute "content"
     */
    public function testPropertyContent()
    {

    }

    /**
     * Test attribute "followup_type"
     */
    public function testPropertyFollowupType()
    {

    }

    /**
     * Test attribute "followup_value"
     */
    public function testPropertyFollowupValue()
    {

    }

    /**
     * Test attribute "formatting_options"
     */
    public function testPropertyFormattingOptions()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "index"
     */
    public function testPropertyIndex()
    {

    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {

    }

}
