<?php
/**
 * ResponseOfEmailTemplateResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CollingMedia\Client;

/**
 * ResponseOfEmailTemplateResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description ResponseOfEmailTemplateResponse
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ResponseOfEmailTemplateResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ResponseOfEmailTemplateResponse"
     */
    public function testResponseOfEmailTemplateResponse()
    {

    }

    /**
     * Test attribute "errors"
     */
    public function testPropertyErrors()
    {

    }

    /**
     * Test attribute "request_id"
     */
    public function testPropertyRequestId()
    {

    }

    /**
     * Test attribute "result"
     */
    public function testPropertyResult()
    {

    }

    /**
     * Test attribute "success"
     */
    public function testPropertySuccess()
    {

    }

    /**
     * Test attribute "warnings"
     */
    public function testPropertyWarnings()
    {

    }

}
