<?php
/**
 * TagResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CollingMedia\Client;

/**
 * TagResponseTest Class Doc Comment
 *
 * @category    Class */
// * @description TagResponse
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TagResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "TagResponse"
     */
    public function testTagResponse()
    {

    }

    /**
     * Test attribute "allowable_values"
     */
    public function testPropertyAllowableValues()
    {

    }

    /**
     * Test attribute "applicable_program_types"
     */
    public function testPropertyApplicableProgramTypes()
    {

    }

    /**
     * Test attribute "required"
     */
    public function testPropertyRequired()
    {

    }

    /**
     * Test attribute "tag_type"
     */
    public function testPropertyTagType()
    {

    }

}
