<?php
/**
 * ThankYouPageRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace CollingMedia\Client;

/**
 * ThankYouPageRequestTest Class Doc Comment
 *
 * @category    Class */
// * @description ThankYouPageRequest
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ThankYouPageRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ThankYouPageRequest"
     */
    public function testThankYouPageRequest()
    {

    }

    /**
     * Test attribute "default"
     */
    public function testPropertyDefault()
    {

    }

    /**
     * Test attribute "followup_type"
     */
    public function testPropertyFollowupType()
    {

    }

    /**
     * Test attribute "followup_value"
     */
    public function testPropertyFollowupValue()
    {

    }

    /**
     * Test attribute "operator"
     */
    public function testPropertyOperator()
    {

    }

    /**
     * Test attribute "subject_field"
     */
    public function testPropertySubjectField()
    {

    }

    /**
     * Test attribute "values"
     */
    public function testPropertyValues()
    {

    }

}
