<?php
/**
 * EmailTemplatesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace CollingMedia\Client;

use \CollingMedia\Client\Configuration;
use \CollingMedia\Client\ApiClient;
use \CollingMedia\Client\ApiException;
use \CollingMedia\Client\ObjectSerializer;

/**
 * EmailTemplatesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EmailTemplatesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for approveDraftUsingPOST1
     *
     * Approve Email Template Draft.
     *
     */
    public function testApproveDraftUsingPOST1()
    {

    }

    /**
     * Test case for cloneTemplateUsingPOST
     *
     * Clone Email Template.
     *
     */
    public function testCloneTemplateUsingPOST()
    {

    }

    /**
     * Test case for createEmailTemplateUsingPOST
     *
     * Create Email Template.
     *
     */
    public function testCreateEmailTemplateUsingPOST()
    {

    }

    /**
     * Test case for deleteTemplateUsingPOST
     *
     * Delete Email Template.
     *
     */
    public function testDeleteTemplateUsingPOST()
    {

    }

    /**
     * Test case for discardDraftUsingPOST1
     *
     * Discard Email Template Draft.
     *
     */
    public function testDiscardDraftUsingPOST1()
    {

    }

    /**
     * Test case for getEmailTemplatesUsingGET
     *
     * Get Email Templates.
     *
     */
    public function testGetEmailTemplatesUsingGET()
    {

    }

    /**
     * Test case for getTemplateByIdUsingGET
     *
     * Get Email Template by Id.
     *
     */
    public function testGetTemplateByIdUsingGET()
    {

    }

    /**
     * Test case for getTemplateByNameUsingGET
     *
     * Get Email Template by Name.
     *
     */
    public function testGetTemplateByNameUsingGET()
    {

    }

    /**
     * Test case for getTemplateContentByIdUsingGET
     *
     * Get Email Template Content by Id.
     *
     */
    public function testGetTemplateContentByIdUsingGET()
    {

    }

    /**
     * Test case for unapproveDraftUsingPOST1
     *
     * Unapprove Email Template Draft.
     *
     */
    public function testUnapproveDraftUsingPOST1()
    {

    }

    /**
     * Test case for updateEmailTemplateContentUsingPOST
     *
     * Update Email Template Content.
     *
     */
    public function testUpdateEmailTemplateContentUsingPOST()
    {

    }

    /**
     * Test case for updateEmailTemplateUsingPOST
     *
     * Update Email Template Metadata.
     *
     */
    public function testUpdateEmailTemplateUsingPOST()
    {

    }

}
