<?php
/**
 * FilesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace CollingMedia\Client;

use \CollingMedia\Client\Configuration;
use \CollingMedia\Client\ApiClient;
use \CollingMedia\Client\ApiException;
use \CollingMedia\Client\ObjectSerializer;

/**
 * FilesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FilesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for createFileUsingPOST
     *
     * Create File.
     *
     */
    public function testCreateFileUsingPOST()
    {

    }

    /**
     * Test case for getFileByIdUsingGET
     *
     * Get File by Id.
     *
     */
    public function testGetFileByIdUsingGET()
    {

    }

    /**
     * Test case for getFileByNameUsingGET
     *
     * Get File by Name.
     *
     */
    public function testGetFileByNameUsingGET()
    {

    }

    /**
     * Test case for getFilesUsingGET
     *
     * Get Files.
     *
     */
    public function testGetFilesUsingGET()
    {

    }

}
