<?php
/**
 * FormsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace CollingMedia\Client;

use \CollingMedia\Client\Configuration;
use \CollingMedia\Client\ApiClient;
use \CollingMedia\Client\ApiException;
use \CollingMedia\Client\ObjectSerializer;

/**
 * FormsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FormsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for approveFromUsingPOST
     *
     * Approve Form Draft.
     *
     */
    public function testApproveFromUsingPOST()
    {

    }

    /**
     * Test case for browseForms2UsingGET
     *
     * Get Forms.
     *
     */
    public function testBrowseForms2UsingGET()
    {

    }

    /**
     * Test case for cloneLpFormsUsingPOST
     *
     * Clone Form.
     *
     */
    public function testCloneLpFormsUsingPOST()
    {

    }

    /**
     * Test case for createLpFormsUsingPOST
     *
     * Create Form.
     *
     */
    public function testCreateLpFormsUsingPOST()
    {

    }

    /**
     * Test case for deleteFormByIdUsingPOST
     *
     * Delete Form.
     *
     */
    public function testDeleteFormByIdUsingPOST()
    {

    }

    /**
     * Test case for discardFormByIdUsingPOST
     *
     * Discard Form Draft.
     *
     */
    public function testDiscardFormByIdUsingPOST()
    {

    }

    /**
     * Test case for getLpFormByIdUsingGET
     *
     * Get Form By Id.
     *
     */
    public function testGetLpFormByIdUsingGET()
    {

    }

    /**
     * Test case for getLpFormByNameUsingGET
     *
     * Get Form by Name.
     *
     */
    public function testGetLpFormByNameUsingGET()
    {

    }

    /**
     * Test case for getThankYouPageByIdUsingGET
     *
     * Get Thank You Page by Form Id.
     *
     */
    public function testGetThankYouPageByIdUsingGET()
    {

    }

    /**
     * Test case for updateFormSubmitButtonUsingPOST
     *
     * Update Submit Button.
     *
     */
    public function testUpdateFormSubmitButtonUsingPOST()
    {

    }

    /**
     * Test case for updateFormsUsingPOST
     *
     * Update Form Metadata.
     *
     */
    public function testUpdateFormsUsingPOST()
    {

    }

    /**
     * Test case for updateThankYouPageByIdUsingPOST
     *
     * Update Thank You Page.
     *
     */
    public function testUpdateThankYouPageByIdUsingPOST()
    {

    }

}
