<?php
/**
 * LandingPageTemplatesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace CollingMedia\Client;

use \CollingMedia\Client\Configuration;
use \CollingMedia\Client\ApiClient;
use \CollingMedia\Client\ApiException;
use \CollingMedia\Client\ObjectSerializer;

/**
 * LandingPageTemplatesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LandingPageTemplatesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for approveLandingPageTemplateUsingPOST
     *
     * Approve Landing Page Template Draft.
     *
     */
    public function testApproveLandingPageTemplateUsingPOST()
    {

    }

    /**
     * Test case for cloneLpTemplateUsingPOST
     *
     * Clone Landing Page Template.
     *
     */
    public function testCloneLpTemplateUsingPOST()
    {

    }

    /**
     * Test case for createLpTemplateUsingPOST
     *
     * Create Landing Page Template.
     *
     */
    public function testCreateLpTemplateUsingPOST()
    {

    }

    /**
     * Test case for deleteLpTemplateUsingPOST
     *
     * Delete Landing Page Template.
     *
     */
    public function testDeleteLpTemplateUsingPOST()
    {

    }

    /**
     * Test case for discardDraftUsingPOST2
     *
     * Discard Landing Page Template Draft.
     *
     */
    public function testDiscardDraftUsingPOST2()
    {

    }

    /**
     * Test case for getLandingPageTemplateByIdUsingGET
     *
     * Get Landing Page Template by Id.
     *
     */
    public function testGetLandingPageTemplateByIdUsingGET()
    {

    }

    /**
     * Test case for getLandingPageTemplateByNameUsingGET
     *
     * Get Landing Page Template by Name.
     *
     */
    public function testGetLandingPageTemplateByNameUsingGET()
    {

    }

    /**
     * Test case for getLandingPageTemplateContentUsingGET
     *
     * Get Landing Page Template Content.
     *
     */
    public function testGetLandingPageTemplateContentUsingGET()
    {

    }

    /**
     * Test case for getLandingPageTemplatesUsingGET
     *
     * Get Landing Page Templates.
     *
     */
    public function testGetLandingPageTemplatesUsingGET()
    {

    }

    /**
     * Test case for unapproveLandingPageTemplateUsingPOST
     *
     * Unapprove Landing Page Template.
     *
     */
    public function testUnapproveLandingPageTemplateUsingPOST()
    {

    }

    /**
     * Test case for updateLandingPageTemplateContentUsingPOST
     *
     * Update Landing Page Template Content.
     *
     */
    public function testUpdateLandingPageTemplateContentUsingPOST()
    {

    }

    /**
     * Test case for updateLpTemplateUsingPOST
     *
     * Update Landing Page Template Metadata.
     *
     */
    public function testUpdateLpTemplateUsingPOST()
    {

    }

}
