<?php
/**
 * LandingPageContentApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace CollingMedia\Client;

use \CollingMedia\Client\Configuration;
use \CollingMedia\Client\ApiClient;
use \CollingMedia\Client\ApiException;
use \CollingMedia\Client\ObjectSerializer;

/**
 * LandingPageContentApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LandingPageContentApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for addLandingPageContentUsingPOST
     *
     * Add Landing Page Content Section.
     *
     */
    public function testAddLandingPageContentUsingPOST()
    {

    }

    /**
     * Test case for getLandingPageContentUsingGET
     *
     * Get Landing Page Content.
     *
     */
    public function testGetLandingPageContentUsingGET()
    {

    }

    /**
     * Test case for getLandingPageDynamicContentsUsingGET
     *
     * Get Landing Page Dynamic Content.
     *
     */
    public function testGetLandingPageDynamicContentsUsingGET()
    {

    }

    /**
     * Test case for removeLandingPageContentUsingPOST
     *
     * Delete Landing Page Content Section.
     *
     */
    public function testRemoveLandingPageContentUsingPOST()
    {

    }

    /**
     * Test case for updateLandingPageContentUsingPOST
     *
     * Update Landing Page Content Section.
     *
     */
    public function testUpdateLandingPageContentUsingPOST()
    {

    }

    /**
     * Test case for updateLandingPageDynamicContentUsingPOST
     *
     * Update Landing Page Dynamic Content Section.
     *
     */
    public function testUpdateLandingPageDynamicContentUsingPOST()
    {

    }

}
