<?php
/**
 * LandingPagesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace CollingMedia\Client;

use \CollingMedia\Client\Configuration;
use \CollingMedia\Client\ApiClient;
use \CollingMedia\Client\ApiException;
use \CollingMedia\Client\ObjectSerializer;

/**
 * LandingPagesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LandingPagesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for approveLandingPageUsingPOST
     *
     * Approve Landing Page Draft.
     *
     */
    public function testApproveLandingPageUsingPOST()
    {

    }

    /**
     * Test case for browseLandingPagesUsingGET
     *
     * Get Landing Pages.
     *
     */
    public function testBrowseLandingPagesUsingGET()
    {

    }

    /**
     * Test case for cloneLandingPageUsingPOST
     *
     * Clone Landing Page.
     *
     */
    public function testCloneLandingPageUsingPOST()
    {

    }

    /**
     * Test case for createLandingPageUsingPOST
     *
     * Create Landing Page.
     *
     */
    public function testCreateLandingPageUsingPOST()
    {

    }

    /**
     * Test case for deleteLandingPageByIdUsingPOST
     *
     * Delete Landing Page.
     *
     */
    public function testDeleteLandingPageByIdUsingPOST()
    {

    }

    /**
     * Test case for discardLandingPageByIdUsingPOST
     *
     * Discard Landing Page Draft.
     *
     */
    public function testDiscardLandingPageByIdUsingPOST()
    {

    }

    /**
     * Test case for getLandingPageByIdUsingGET
     *
     * Get Landing Page by Id.
     *
     */
    public function testGetLandingPageByIdUsingGET()
    {

    }

    /**
     * Test case for getLandingPageByNameUsingGET
     *
     * Get Landing Page by Name.
     *
     */
    public function testGetLandingPageByNameUsingGET()
    {

    }

    /**
     * Test case for getVariablesUsingGET
     *
     * getVariables.
     *
     */
    public function testGetVariablesUsingGET()
    {

    }

    /**
     * Test case for unapproveLandingPageByIdUsingPOST
     *
     * Unapprove Landing Page.
     *
     */
    public function testUnapproveLandingPageByIdUsingPOST()
    {

    }

    /**
     * Test case for updateLandingPageUsingPOST
     *
     * Update Landing Page Metadata.
     *
     */
    public function testUpdateLandingPageUsingPOST()
    {

    }

    /**
     * Test case for updateLandingPageVariableUsingPOST
     *
     * updateLandingPageVariable.
     *
     */
    public function testUpdateLandingPageVariableUsingPOST()
    {

    }

}
