<?php
/**
 * ProgramsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Marketo Rest API
 *
 * Marketo Rest API
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace CollingMedia\Client;

use \CollingMedia\Client\Configuration;
use \CollingMedia\Client\ApiClient;
use \CollingMedia\Client\ApiException;
use \CollingMedia\Client\ObjectSerializer;

/**
 * ProgramsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProgramsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for approveProgramUsingPOST
     *
     * Approve Program.
     *
     */
    public function testApproveProgramUsingPOST()
    {

    }

    /**
     * Test case for browseProgramsUsingGET
     *
     * Get Programs.
     *
     */
    public function testBrowseProgramsUsingGET()
    {

    }

    /**
     * Test case for cloneProgramUsingPOST
     *
     * Clone Program.
     *
     */
    public function testCloneProgramUsingPOST()
    {

    }

    /**
     * Test case for createProgramUsingPOST
     *
     * Create Program.
     *
     */
    public function testCreateProgramUsingPOST()
    {

    }

    /**
     * Test case for deleteProgramUsingPOST
     *
     * Delete Program.
     *
     */
    public function testDeleteProgramUsingPOST()
    {

    }

    /**
     * Test case for getProgramByIdUsingGET
     *
     * Get Program by Id.
     *
     */
    public function testGetProgramByIdUsingGET()
    {

    }

    /**
     * Test case for getProgramByNameUsingGET
     *
     * Get Program by Name.
     *
     */
    public function testGetProgramByNameUsingGET()
    {

    }

    /**
     * Test case for getProgramListByTagUsingGET
     *
     * Get Programs by Tag.
     *
     */
    public function testGetProgramListByTagUsingGET()
    {

    }

    /**
     * Test case for unapproveProgramUsingPOST
     *
     * Unapprove Program.
     *
     */
    public function testUnapproveProgramUsingPOST()
    {

    }

    /**
     * Test case for updateProgramUsingPOST
     *
     * Update Program Metadata.
     *
     */
    public function testUpdateProgramUsingPOST()
    {

    }

}
